from . import mlp
from . import lenet
from . import resnet
from . import senet
from . import resnet_trp
from . import customnet
from . import resnet_SVD
from . import customnet_SVD
from . import alexnet
from . import resnet_origin
from . import vgg_16_bn